
services:

  llmserver:
    container_name: llmserver
    build:
      context: ./LLMServer
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    ports:
      - "5006:5006"
    environment:
      - MYSQL_HOST = mysql
      - POSTGRES_HOST = postgres
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - postgres
      - redis

  api:
    container_name: api
    build:
      context: ./API
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    ports:
      - "5003:5003"
    environment:
      - MYSQL_HOST = mysql
      - POSTGRES_HOST = postgres
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - postgres
      - redis
      - llmserver

  autojob:
    build:
      context: ./AutoJob
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    environment:
      - MYSQL_HOST = mysql
      - POSTGRES_HOST = postgres
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - postgres
      - redis
      - llmserver
      - api

  web_manage:
    container_name: web_manage
    build:
      context: ./Web.Manage
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/shared
    ports:
      - "5002:5002"
    environment:
      - MYSQL_HOST = mysql
      - POSTGRES_HOST = postgres
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - postgres
      - redis
      - autojob
      - llmserver
      - api


  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
    restart: always
    environment:
      - TZ=Asia/Shanghai

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: xinling_knowledge_base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:5.0.10
    container_name: redis_5.0.10
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    environment:
      - TZ=Asia/Shanghai

volumes:
  postgres_data: {}
  mysql_data: {}
  redis_data: {}
  shared_volume: {}